# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61dca89e1e8d0deb3566e3aca8e4afa5b3bc8b2b3d707a04a91b9320f4e6b1ad3516a9a0d16d896232d2f6817803ebe5c28e2c98baacb6354bb01021a7fe30ef

test:
  secret_key_base: 57ab2f5234fe5db14fdcd7f45b4ce0f4dc0524d7a86ed8c40523658df7b618d3a0ebfecb0fdc1e609a8b585ffa686ccc9d15fb633b80da292a9c95d7449295d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
